In [1]:

import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio.mask import mask
import rasterstats as rstats
import xarray as xr
import matplotlib.pyplot as plt

### Compare original and downscaled NEE, for all time

In [13]:
# Function to compute mean NEE for each MSA
def calculate_msa_mean(raster_file, msa_gdf):
    mean_values = []
    for _, row in msa_gdf.iterrows():
        msa_geometry = [row['geometry']]
        with rasterio.open(raster_file) as src:
            out_image, _ = mask(src, msa_geometry, crop=True, nodata=np.nan)
            out_image = out_image[0]
        
        # Compute mean ignoring NaNs
        mean_value = np.nanmean(out_image) if np.any(~np.isnan(out_image)) else np.nan
        mean_values.append(mean_value)
    return mean_values

def calc_MSA_NEE_mean_compare(year_month, msa_gdf_crsdownscaled, msa_gdf_crs4326, nee_orig_transform):
    '''
    Param:
        year_month(str): e.g.'200101'
    Return:
        two lists: 'nee_downscaled_msa_mean_{year_month}', 'nee_orig_msa_mean_{year_month}'
    '''
    print(f'Processing {year_month}...')

    # Read the downscaled NEE raster
    downscaled_nee_file_path = f'../gis/output/downscaledNEE/downscaledNEE_US_{year_month}.tif'
    with rasterio.open(downscaled_nee_file_path) as src:
        downscaled_nee = src.read(1)
        downscaled_nee = np.where(downscaled_nee == src.nodata, np.nan, downscaled_nee)

    # Compute mean NEE for downscaled data
    nee_downscaled_msa_mean = calculate_msa_mean(downscaled_nee_file_path, msa_gdf_crsdownscaled)


    # get original NEE value for specific year month
    original_nee_file_path = f'../gis/NEE/NEE.RS.FP-NONE.MLM-ALL.METEO-NONE.4320_2160.monthly.{year_month[:4]}.nc'
    variable = 'NEE'
    ds = xr.open_dataset(original_nee_file_path)
    original_nee = ds[variable][int(year_month[4:]) - 1].values  # Extract data for the specified month

    nee_orig_msa_mean = []

    # calculate mean original NEE for each MSA
    for index, row in msa_gdf_crs4326.iterrows():
        shape_info = row['geometry']
        name = row['NAMELSAD']
        # go through all geometries and compute zonal statistics
        res = rstats.zonal_stats(shape_info, original_nee, affine=nee_orig_transform, stats="mean")
        mean = res[0]['mean']
        # print(name, mean)
        nee_orig_msa_mean.append(mean)

    msa_mean_dict = {
        f'nee_downscaled_msa_mean_{year_month}': nee_downscaled_msa_mean,
        f'nee_orig_msa_mean_{year_month}': nee_orig_msa_mean
    }

    return msa_mean_dict

In [ ]:
# ====== prepare files and parameters like crs =====

msa_file = '../gis/msa/msaUS_mland_aea1_M1_all.shp' # TODO: change the file path to your MSA shapefile
# msa_gdf = gpd.read_file(msa_file)
msa_gdf_crsaea = gpd.read_file(msa_file)

# get NEE crs which is equal to GPP crs (EPSG:4326)
gpp_file = f'../gis/GPP_monthly_mean/gpp_200101.tif'
with rasterio.open(gpp_file) as gpp_dstrd:
    gpp_crs = gpp_dstrd.crs
nee_crs = gpp_crs


# get original NEE transform
minx, miny, maxx, maxy = -180.0, -90.0, 180.0, 90.0
nee_orig_resolution_x = 1/12
nee_orig_resolution_y = 1/12
nee_orig_transform = rasterio.transform.from_origin(minx, maxy, nee_orig_resolution_x, nee_orig_resolution_y)

with rasterio.open('../gis/output/downscaledNEE/downscaledNEE_US_200101.tif') as t:
    downscaled_nee_meta = t.meta.copy()
    
# Ensure CRS match between raster and shapefile
msa_gdf_crsdownscaled = msa_gdf_crsaea.to_crs(downscaled_nee_meta['crs'])

# make sure msa and nee are in same crs
msa_gdf_crs4326 = msa_gdf_crsaea.to_crs(nee_crs)

# ====== calculate =====
# add the mean values to the msa dataframe
msa_mean_compare = msa_gdf_crsaea[['NAMELSAD']]
for year in range(2001, 2016):
    for month in range(1, 13):
        year_month = f'{year}{month:02}'
        msa_mean_dict = calc_MSA_NEE_mean_compare(year_month, msa_gdf_crsdownscaled, msa_gdf_crs4326, nee_orig_transform)
        for key, value in msa_mean_dict.items():
            msa_mean_compare[key] = value

msa_mean_compare_file = '../gis/output/statistics/msa_mean_compare.csv'
msa_mean_compare.to_csv('../gis/output/statistics/msa_mean_compare.csv', index=False)

Processing 200101...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value

Processing 200102...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value

Processing 200103...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value

Processing 200104...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  msa_mean_compare[key] = value

Processing 200105...
Processing 200106...
Processing 200107...
Processing 200108...
Processing 200109...
Processing 200110...
Processing 200111...
Processing 200112...
Processing 200201...
Processing 200202...
Processing 200203...
Processing 200204...
Processing 200205...
Processing 200206...
Processing 200207...
Processing 200208...
Processing 200209...
Processing 200210...
Processing 200211...
Processing 200212...
Processing 200301...
Processing 200302...
Processing 200303...
Processing 200304...
Processing 200305...
Processing 200306...
Processing 200307...
Processing 200308...
Processing 200309...
Processing 200310...
Processing 200311...
Processing 200312...
Processing 200401...
Processing 200402...
Processing 200403...
Processing 200404...
Processing 200405...
Processing 200406...
Processing 200407...
Processing 200408...
Processing 200409...
Processing 200410...
Processing 200411...
Processing 200412...
Processing 200501...
Processing 200502...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200503...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200504...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200505...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200506...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200507...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200508...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200509...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200510...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200511...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200512...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200601...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200602...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200603...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200604...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200605...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200606...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200607...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200608...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200609...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200610...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200611...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200612...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200701...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200702...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200703...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200704...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200705...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200706...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200707...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200708...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200709...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200710...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200711...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200712...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200801...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200802...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200803...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200804...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200805...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200806...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200807...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200808...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200809...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200810...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200811...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200812...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200901...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200902...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200903...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200904...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200905...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200906...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200907...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200908...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200909...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200910...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200911...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 200912...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201001...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201002...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201003...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201004...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201005...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201006...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201007...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201008...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201009...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201010...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201011...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201012...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201101...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201102...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201103...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201104...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201105...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201106...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201107...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201108...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201109...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201110...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201111...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201112...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201201...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201202...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201203...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201204...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201205...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201206...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201207...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201208...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201209...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201210...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201211...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201212...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201301...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201302...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201303...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201304...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201305...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201306...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201307...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201308...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201309...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201310...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201311...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201312...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201401...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201402...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201403...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201404...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201405...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201406...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201407...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201408...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201409...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201410...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201411...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201412...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201501...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201502...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201503...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201504...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201505...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201506...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201507...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201508...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201509...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201510...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201511...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

Processing 201512...

C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value
C:\Users\qifanw\AppData\Local\Temp\1\ipykernel_14800\2003268973.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  msa_mean_compare[key] = value

In [22]:
import pandas as pd

# Load the CSV file
df = pd.read_csv(msa_mean_compare_file)

# Extract the relevant columns for downscaled and original values
downscaled_cols = [col for col in df.columns if 'nee_downscaled_msa_mean' in col]
orig_cols = [col for col in df.columns if 'nee_orig_msa_mean' in col]

# Compute yearly means
yearly_mean_df = pd.DataFrame({'NAMELSAD': df['NAMELSAD']})

for year in range(2001, 2016):
    yearly_downscaled_cols = [col for col in downscaled_cols if str(year) in col]
    yearly_orig_cols = [col for col in orig_cols if str(year) in col]

    yearly_mean_df[f'nee_downscaled_yearly_mean_{year}'] = df[yearly_downscaled_cols].mean(axis=1)
    yearly_mean_df[f'nee_orig_yearly_mean_{year}'] = df[yearly_orig_cols].mean(axis=1)
    yearly_mean_df[f'nee_ratio_yearly_{year}'] = yearly_mean_df[f'nee_downscaled_yearly_mean_{year}'] / yearly_mean_df[f'nee_orig_yearly_mean_{year}']

# Compute mean for each month across all years
monthly_mean_df = pd.DataFrame({'NAMELSAD': df['NAMELSAD']})

for month in range(1, 13):
    month_str = f'{month:02d}'
    monthly_downscaled_cols = [col for col in downscaled_cols if col.endswith(month_str)]
    monthly_orig_cols = [col for col in orig_cols if col.endswith(month_str)]

    monthly_mean_df[f'nee_downscaled_monthly_mean_{month_str}'] = df[monthly_downscaled_cols].mean(axis=1)
    monthly_mean_df[f'nee_orig_monthly_mean_{month_str}'] = df[monthly_orig_cols].mean(axis=1)
    monthly_mean_df[f'nee_ratio_monthly_{month_str}'] = monthly_mean_df[f'nee_downscaled_monthly_mean_{month_str}'] / monthly_mean_df[f'nee_orig_monthly_mean_{month_str}']

In [31]:
1 / 1.2

0.8333333333333334

In [32]:
# Define the tolerance level
tolerance = 1.2

# Count occurrences where the yearly ratio deviates from 1
yearly_ratio_cols = [col for col in yearly_mean_df.columns if 'nee_ratio_yearly_' in col]
yearly_mean_df[f'exceeding_tolerance_{tolerance}_count'] = yearly_mean_df[yearly_ratio_cols].apply(lambda x: ((x < (1 / tolerance)) | (x > (tolerance))).sum(), axis=1)

# Count occurrences where the monthly ratio deviates from 1
monthly_ratio_cols = [col for col in monthly_mean_df.columns if 'nee_ratio_monthly_' in col]
monthly_mean_df[f'exceeding_tolerance_{tolerance}_count'] = monthly_mean_df[monthly_ratio_cols].apply(lambda x: ((x < (1 / tolerance)) | (x > (tolerance))).sum(), axis=1)

In [33]:
yearly_mean_df.to_csv('../gis/output/analysis/nee_downscale_orig_compare_yearly.csv', index=False)
monthly_mean_df.to_csv('../gis/output/analysis/nee_downscale_orig_compare_monthly.csv', index=False)

In [37]:
yearly_mean_df.sort_values(by=f'exceeding_tolerance_{tolerance}_count', ascending=False).head(20)[['NAMELSAD', f'exceeding_tolerance_{tolerance}_count']]

,NAMELSAD,exceeding_tolerance_1.2_count
325,"San Jose-Sunnyvale-Santa Clara, CA Metro Area",15
294,"Portland-Vancouver-Hillsboro, OR-WA Metro Area",15
259,"Monroe, LA Metro Area",15
73,"Yakima, WA Metro Area",15
338,"Spokane-Spokane Valley, WA Metro Area",15
309,"Yuba City, CA Metro Area",14
299,"Pueblo, CO Metro Area",9
157,"Davenport-Moline-Rock Island, IA-IL Metro Area",7
203,"Muncie, IN Metro Area",6
170,"Las Cruces, NM Metro Area",6
230,"Lincoln, NE Metro Area",6
68,"Yuma, AZ Metro Area",6
138,"Kankakee, IL Metro Area",4
10,"Lake Havasu City-Kingman, AZ Metro Area",3
144,"Sandusky, OH Metro Area",3
158,"Springfield, OH Metro Area",3
217,"Lawrence, KS Metro Area",2
241,"Janesville-Beloit, WI Metro Area",2
252,"Midland, TX Metro Area",2
242,"Mankato, MN Metro Area",2

In [39]:
monthly_mean_df.sort_values(by=f'exceeding_tolerance_{tolerance}_count', ascending=False).head(20)[['NAMELSAD', f'exceeding_tolerance_{tolerance}_count']]

,NAMELSAD,exceeding_tolerance_1.2_count
325,"San Jose-Sunnyvale-Santa Clara, CA Metro Area",12
294,"Portland-Vancouver-Hillsboro, OR-WA Metro Area",12
309,"Yuba City, CA Metro Area",12
259,"Monroe, LA Metro Area",12
172,"Evansville, IN Metro Area",12
338,"Spokane-Spokane Valley, WA Metro Area",12
73,"Yakima, WA Metro Area",10
10,"Lake Havasu City-Kingman, AZ Metro Area",9
299,"Pueblo, CO Metro Area",6
16,"San Luis Obispo-Paso Robles, CA Metro Area",5
304,"Carson City, NV Metro Area",5
296,"Albany, OR Metro Area",4
76,"Twin Falls, ID Metro Area",4
14,"Grand Junction, CO Metro Area",4
252,"Midland, TX Metro Area",3
32,"Logan, UT-ID Metro Area",3
117,"Boise City, ID Metro Area",3
48,"Laredo, TX Metro Area",2
267,"Slidell-Mandeville-Covington, LA Metro Area",2
157,"Davenport-Moline-Rock Island, IA-IL Metro Area",2

### save original nee from netcdf to tiff for comparison

In [44]:
year_month = '200601'
orig_nee_file = f'../gis/NEE/NEE.RS.FP-NONE.MLM-ALL.METEO-NONE.4320_2160.monthly.{year_month[:4]}.nc'

orig_nee_ds = xr.open_dataset(orig_nee_file)
orig_nee_time_file = f'../gis/output/originalNEE_{year_month}.tif'

time_slice = orig_nee_ds['NEE'][int(year_month[4:]) - 1].values

with rasterio.open(
    orig_nee_time_file,
    'w',
    driver='GTiff',
    height=time_slice.shape[0],
    width=time_slice.shape[1],
    count=1,
    dtype=str(time_slice.dtype),
    crs='EPSG:4326',  # Assuming WGS84 projection
    transform=nee_orig_transform,
) as dst:
    dst.write(time_slice, 1)